controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
create_task:
    path: /create_task
    controller: App\Controller\TaskController::create